# Generated by Django 4.0.2 on 2022-02-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournesol', '0026_remove_comparison_poll_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='tournesol_score',
            field=models.IntegerField(default=0, help_text='Total number of certified contributors who rated the video'),
        ),
    ]
