# Generated by Django 4.0.2 on 2022-02-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournesol', '0027_entity_tournesol_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='tournesol_score',
            field=models.IntegerField(default=0, help_text='Total number of pairwise comparisons for this videofrom certified contributors'),
        ),
    ]
