# Generated by Django 4.0.2 on 2022-02-18 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournesol', '0027_alter_entity_metadata'),
        ('tournesol', '0029_alter_entity_tournesol_score'),
    ]

    operations = [
    ]
