# Generated by Django 4.0.2 on 2022-02-18 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournesol', '0030_merge_20220218_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='tournesol_score',
        ),
    ]
