# Generated by Django 4.0.2 on 2022-02-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournesol', '0031_remove_entity_tournesol_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='tournesol_score',
            field=models.FloatField(default=0, help_text='Tournesol Scorefrom certified contributors'),
        ),
    ]
